fix(karakeep): drop the flag meilisearch v1.51 removed
#4194 bumped meilisearch v1.50.0 to v1.51.0, which graduated dumpless upgrade
out of experimental and removed the flag. The pinned arg now aborts startup:

  error: unexpected argument '--experimental-dumpless-upgrade' found

The container has been CrashLoopBackOff since, taking karakeep search down.